/**
 * Bundles the routing endpoint into api/route.js.
 *
 * Vercel compiles every file in api/ by itself and does not follow imports out
 * of that directory, so a function that reaches into src/ deploys as a file
 * whose imports cannot be resolved at runtime. Bundling first leaves one file
 * with nothing to resolve.
 *
 * esbuild is already here — vite brings it — so this adds no dependency.
 */
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';

await mkdir('api', { recursive: true });

await build({
  entryPoints: ['server/route.ts'],
  outfile: 'api/route.js',
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  // Imports in this project carry a .ts extension, which node needs to run the
  // tests straight from source. esbuild resolves them as written.
  resolveExtensions: ['.ts', '.js', '.mjs', '.json'],
  banner: { js: '// Generated by scripts/build-api.mjs from server/route.ts. Do not edit.' },
  logLevel: 'info',
});
