/**
 * Bundles the routing endpoint into api/route.js.
 *
 * Why a bundle at all: Vercel compiles every file in api/ by itself and does
 * not follow imports out of that directory, so a function that reaches into
 * src/ deploys as a file whose imports cannot be resolved and dies on the first
 * call with `Cannot find module '/var/task/src/core/chain.ts'`. Flattening the
 * module graph into one file leaves nothing to resolve.
 *
 * Why this is hand-written rather than a call to a bundler: it has to run in
 * places where installing one is not possible, and this project's needs are
 * small — a handful of files, plain ES modules, no dynamic imports, no
 * circular edges. Node's own type stripper does the TypeScript half. What is
 * left is ordering the modules so a definition precedes its use, deleting the
 * import and export keywords that only made sense between files, and refusing
 * to proceed if two modules define the same name, since silently letting one
 * win is exactly the kind of bug that would take a day to find.
 *
 * The result is committed rather than ignored, because Vercel decides what is
 * a function from the files in the repository, not from what a build leaves
 * behind: generated into an ignored path, it is simply never served. Run
 * `npm run build` after touching anything under src/core or server/, and
 * commit what changes.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { stripTypeScriptTypes } from 'node:module';
import { dirname, resolve, relative } from 'node:path';

const ENTRY = resolve('server/route.ts');
const OUT = resolve('api/route.js');

/** Every `import ... from './x.ts'` line, whatever shape it takes. */
const IMPORT = /^import\s+[\s\S]*?from\s*['"]([^'"]+)['"];?[ \t]*$/gm;
/** `export { a, b };` — meaningful between files, meaningless inside one. */
const REEXPORT = /^export\s*\{[^}]*\}\s*;?[ \t]*$/gm;

const order = [];
const seen = new Set();

/** Depth first, children before parents, so a definition precedes its use. */
async function visit(file) {
  if (seen.has(file)) return;
  seen.add(file);
  const source = await readFile(file, 'utf8');
  for (const m of source.matchAll(IMPORT)) {
    if (!m[1].startsWith('.')) throw new Error(`${file} imports ${m[1]}; only relative imports can be flattened`);
    await visit(resolve(dirname(file), m[1]));
  }
  order.push({ file, source });
}

await visit(ENTRY);

const declared = new Map();
const chunks = [];

for (const { file, source } of order) {
  const isEntry = file === ENTRY;
  let code = stripTypeScriptTypes(source, { mode: 'strip' });
  code = code.replace(IMPORT, '').replace(REEXPORT, '');
  // `export default` stays on the entry — that is what Vercel calls. Every
  // other `export` was only ever a door between files that no longer exist.
  code = isEntry
    ? code.replace(/^export\s+(?!default\b)/gm, '')
    : code.replace(/^export\s+(?:default\s+)?/gm, '');

  for (const m of code.matchAll(/^(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)/gm)) {
    const name = m[1];
    const previous = declared.get(name);
    if (previous) {
      throw new Error(
        `${relative(process.cwd(), file)} and ${relative(process.cwd(), previous)} both define \`${name}\`. ` +
          `Flattening them would silently drop one — rename it in one of the two.`,
      );
    }
    declared.set(name, file);
  }

  chunks.push(`/* ===== ${relative(process.cwd(), file)} ===== */\n${code.trim()}\n`);
}

const banner = [
  '// Generated by scripts/build-api.mjs from server/route.ts. Do not edit.',
  '// One file with no imports: Vercel compiles each file in api/ alone and',
  '// does not follow imports out of it.',
  '',
].join('\n');

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, banner + chunks.join('\n'));
console.log(`api/route.js — ${order.length} modules, ${declared.size} top-level names`);
