// Generated by scripts/build-api.mjs from server/route.ts. Do not edit.
// One file with no imports: Vercel compiles each file in api/ alone and
// does not follow imports out of it.
/* ===== src/core/rpc.ts ===== */
/**
 * Talking to the chain, and the wire format it talks in.
 *
 * Kept apart from everything that uses it for a reason that is not tidiness:
 * chain.ts reads pools, v3.ts and v4.ts quote them, and all three need this
 * transport. When it lived in chain.ts the modules imported each other in a
 * circle, which a browser tolerates and a server bundle does not — it loaded
 * the cycle and died on the first call, in under half a second, with nothing
 * in the log to say why.
 */

const RPC_URL = 'https://rpc.mainnet.chain.robinhood.com';

/**
 * Where to go when the browser refuses the direct answer.
 *
 * The public RPC intermittently sends Access-Control-Allow-Origin twice — the
 * browser reports it as "*,*" and drops the response. It clears up on its own
 * within a minute, but a visitor who lands during one of those windows sees a
 * page claiming live data and showing none. So every call goes direct first and
 * only falls back to this pass-through, which forwards the same body to the same
 * endpoint and adds a header the browser will accept. See api/rpc.ts.
 */
const RPC_FALLBACK = '/api/rpc';

/** The public RPC rejects batches larger than this. Measured, not guessed: 50 is accepted, 100 is refused. */
const MAX_BATCH = 40;

                       
             
               
 

const word = (n                 ) => n.toString(16).padStart(64, '0');
const addrWord = (a        ) => a.toLowerCase().replace(/^0x/, '').padStart(64, '0');
/** The low 20 bytes of a 32-byte word. */
const readAddress = (w        ) => '0x' + w.slice(-40);
const readUint = (hex        , slot        ) =>
  BigInt('0x' + hex.slice(2 + slot * 64, 2 + (slot + 1) * 64));

/**
 * The first word of a return value, or null if there isn't one.
 *
 * Distinct from readUint above, which indexes into a return value it trusts to
 * be long enough. A quoter that reverts answers with nothing, and the caller
 * needs to be able to tell that apart from an answer of zero.
 */
const readFirstUint = (hex        )                =>
  hex && hex.length >= 66 ? BigInt('0x' + hex.slice(2, 66)) : null;

/** A number as a 32-byte word, for hand-encoded call data. */
const numWord = (n                 ) => BigInt(n).toString(16).padStart(64, '0');

/** Decodes a solidity `string` return value. Falls back to null on bytes32-style symbols. */
function readString(hex        )                {
  if (!hex || hex.length < 130) return null;
  try {
    const len = Number(readUint(hex, 1));
    if (!Number.isFinite(len) || len === 0 || len > 128) return null;
    const bytes = hex.slice(130, 130 + len * 2);
    if (bytes.length < len * 2) return null;
    const out = decodeURIComponent(bytes.replace(/(..)/g, '%$1'));
    return /^[\x20-\x7e]+$/.test(out) ? out : null;
  } catch {
    return null;
  }
}

/** getReserves() -> (uint112 reserve0, uint112 reserve1, uint32 blockTimestampLast) */
function readReserves(hex        )                          {
  if (!hex || hex.length < 2 + 3 * 64) return null;
  return [readUint(hex, 0), readUint(hex, 1)];
}

                                                                            

/**
 * Sends eth_call in JSON-RPC batches, in order, never more than MAX_BATCH at a
 * time. Returns one hex string (or null) per call, aligned with the input.
 */
                     
                  
                    
                   
                                                                         
                   
     
                                                        
    
                                                                            
                                                                               
                                                                            
                                                                                
                                      
     
                       
 

const wait = (ms        ) => new Promise((r) => setTimeout(r, ms));

/**
 * A 429, carrying what the endpoint asked us to wait when it said.
 *
 * Written out longhand rather than as a parameter property, because the test
 * suite runs this file straight through node's type stripping, which refuses
 * that shorthand.
 */
class Throttled extends Error {
  waitMs               ;
  constructor(waitMs               ) {
    super('rpc 429');
    this.waitMs = waitMs;
  }
}

/**
 * How long to wait before each further attempt.
 *
 * The public endpoint throttles, and it throttles a datacenter address far
 * harder than a browser: the first deploy of the routing endpoint answered
 * `rpc 429` while the same code in a visitor's tab was fine. Half a second is
 * not enough to clear that, so the waits grow into seconds, and when the
 * endpoint says how long to wait, that is used instead of guessing.
 */
const BACKOFF_MS = [600, 1500, 3000, 5000];

/** Whatever Retry-After says, in ms, if it says anything usable. */
function retryAfterMs(res          )                {
  const raw = (res.headers                       )?.get?.('retry-after');
  const secs = Number(raw);
  return Number.isFinite(secs) && secs > 0 ? Math.min(secs * 1000, 8_000) : null;
}

/**
 * One request, with backoff.
 *
 * The public endpoint is rate limited — hit it too fast and the request either
 * comes back 429 or fails outright. Every call therefore backs off and tries
 * again rather than tearing the whole page down.
 */
async function send(body         , io    )                   {
  const direct = io.rpcUrl ?? RPC_URL;
  const f          = io.fetcher ?? ((u, i) => fetch(u, i));
  const tries = io.retries ?? BACKOFF_MS.length;
  // Direct first, every time. The spare is only reached once the endpoint has
  // refused every attempt, and it is dropped again on the next call.
  const spare = io.fetcher ? null : (io.fallbackUrl ?? (io.rpcUrl ? null : RPC_FALLBACK));
  const routes = spare ? [direct, spare] : [direct];
  let last          = null;

  for (const url of routes) {
    for (let attempt = 0; attempt < tries; attempt++) {
      try {
        const res = await f(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
        });
        if (res.status === 429) throw new Throttled(retryAfterMs(res));
        if (!res.ok) throw new Error(`rpc ${res.status}`);
        return await res.json();
      } catch (err) {
        last = err;
        if (attempt < tries - 1) {
          const asked = err instanceof Throttled ? err.waitMs : null;
          await wait(asked ?? BACKOFF_MS[attempt] ?? 5_000);
        }
      }
    }
  }
  throw last instanceof Error ? last : new Error('rpc unreachable');
}

/** A single JSON-RPC call that is not eth_call. */
async function rpc   (method        , params           , io     = {})             {
  const json = (await send({ jsonrpc: '2.0', id: 1, method, params }, io))     
               
                                 
   ;
  if (json.error) throw new Error(json.error.message ?? method);
  return json.result     ;
}

/**
 * Sends eth_call in JSON-RPC batches, in order, never more than MAX_BATCH at a
 * time. Returns one hex string (or null) per call, aligned with the input.
 */
async function ethCallBatch(calls        , io     = {})                             {
  const pause = io.pauseMs ?? 220;
  const out                    = new Array(calls.length).fill(null);

  for (let start = 0; start < calls.length; start += MAX_BATCH) {
    const slice = calls.slice(start, start + MAX_BATCH);
    const body = slice.map((c, i) => ({
      jsonrpc: '2.0',
      id: i,
      method: 'eth_call',
      params: [{ to: c.to, data: c.data }, 'latest'],
    }));
    const json = (await send(body, io))                                          ;
    for (const entry of json) {
      if (typeof entry.id === 'number' && typeof entry.result === 'string') {
        out[start + entry.id] = entry.result;
      }
    }
    if (start + MAX_BATCH < calls.length && pause > 0) await wait(pause);
  }
  return out;
}

/* ===== src/core/v3.ts ===== */
/**
 * Concentrated liquidity: asking Uniswap V3 what a swap actually costs.
 *
 * The V2 side of this project estimates slippage as S / L, which is only valid
 * for a constant-product pool. V3 holds its liquidity in ticks, so that formula
 * does not describe it at all. Rather than stretch the estimate over a market it
 * does not fit, this module asks the pool's own quoter: QuoterV2 simulates the
 * swap on current state and returns the exact output.
 *
 * Cost of a hop is defined as what the trade loses against the pool's own
 * marginal price:
 *
 *     cost = 1 - rate(S) / rate(0)          rate = amountOut / amountIn
 *
 * rate(0) is taken from a trade small enough to cross no ticks, so it is the
 * marginal price minus the fee; dividing it back out by (1 - fee) recovers the
 * fee-free price and makes the fee part of the cost, exactly as it is for V2.
 *
 * Checked against the chain: at a trade of 0.001 WETH the cost this produces
 * comes out at 0.010%, 0.050%, 0.300% and 1.000% on the four fee tiers — the
 * fee, to three decimals, with nothing left over.
 *
 * What this does NOT model, stated plainly: two pools of the same pair can sit
 * at slightly different prices, and a real router would arbitrage that. Here
 * every pool is measured against its own marginal price, so a pool that is
 * simply priced worse does not look more expensive.
 *
 * Addresses from github.com/Uniswap/contracts, deployments/4663.md.
 */



const V3_FACTORY = '0x1f7d7550b1b028f7571e69a784071f0205fd2efa';
const QUOTER_V2 = '0x33e885ed0ec9bf04ecfb19341582aadcb4c8a9e7';

/** The four fee tiers Uniswap deploys, in hundredths of a basis point. */
const FEE_TIERS = [100, 500, 3000, 10_000]         ;

const SEL_V3 = {
  /** getPool(address,address,uint24) */
  getPool: '0x1698ee82',
  /** quoteExactInputSingle((address,address,uint256,uint24,uint160)) */
  quote: '0xc6a5026a',
}         ;


                         
                  
                   
              
               
 

/**
 * Which of the four tiers actually exist for these pairs.
 * One eth_call per pair per tier; a pair with no pool answers with the zero address.
 */
async function findV3Pools(
  pairs                                              ,
  io     = {},
)                    {
  const calls         = [];
  const meta                                                            = [];
  for (const p of pairs) {
    for (const fee of FEE_TIERS) {
      calls.push({
        to: V3_FACTORY,
        data: SEL_V3.getPool + addrWord(p.tokenIn) + addrWord(p.tokenOut) + numWord(fee),
      });
      meta.push({ ...p, fee });
    }
  }
  const answers = await ethCallBatch(calls, io);
  const out           = [];
  answers.forEach((hex, i) => {
    if (!hex) return;
    const pool = readAddress(hex);
    if (/^0x0+$/.test(pool)) return;
    out.push({ ...meta[i], pool });
  });
  return out;
}

                         
                  
                   
              
               
                                                                               
                                     
 

/** A trade small enough to cross no ticks, so its rate is the marginal one. */
const probeOf = (amountIn        ) => {
  const p = amountIn / 1000n;
  return p > 0n ? p : 1n;
};

/**
 * Quotes every pool at every trade size, plus one probe each.
 *
 * The whole ladder is asked for in one go so the page can switch trade size
 * without going back to the chain: a dropdown that takes ten seconds to answer
 * is a dropdown nobody touches.
 */
async function quoteV3(
  pools          ,
  /** Trade size in dollars -> amount of tokenIn, in its own decimals. */
  amountInOf                                              ,
  sizesUsd          ,
  io     = {},
)                    {
  if (pools.length === 0 || sizesUsd.length === 0) return [];

  const calls         = [];
  const plan                                                          = [];

  for (const p of pools) {
    const sizes = sizesUsd.map((usd) => amountInOf(p.tokenIn, usd));
    const probe = probeOf(sizes[0]);
    plan.push({ pool: p, sizes, probe });
    const q = (amount        ) => ({
      to: QUOTER_V2,
      data:
        SEL_V3.quote +
        addrWord(p.tokenIn) +
        addrWord(p.tokenOut) +
        numWord(amount) +
        numWord(p.fee) +
        numWord(0),
    });
    for (const amount of sizes) calls.push(q(amount));
    calls.push(q(probe));
  }

  const answers = await ethCallBatch(calls, io);

  const out           = [];
  let cursor = 0;
  for (const { pool, sizes, probe } of plan) {
    const results = answers.slice(cursor, cursor + sizes.length + 1);
    cursor += sizes.length + 1;

    const probeOut = readFirstUint(results[sizes.length] ?? '');
    if (probeOut === null || probeOut <= 0n) continue;
    const probeRate = Number(probeOut) / Number(probe);
    if (!isFinite(probeRate) || probeRate <= 0) continue;

    // The probe rate already has the fee taken out of it; dividing it back in
    // recovers the fee-free price, so the fee counts as cost exactly as on V2.
    const marginal = probeRate / (1 - pool.fee / 1e6);

    const costBySize                         = {};
    sizes.forEach((amountIn, i) => {
      const amountOut = readFirstUint(results[i] ?? '');
      if (amountOut === null || amountOut <= 0n) return;
      const rate = Number(amountOut) / Number(amountIn);
      const cost = 1 - rate / marginal;
      if (isFinite(cost)) costBySize[sizesUsd[i]] = Math.max(cost, 0);
    });

    if (Object.keys(costBySize).length > 0) out.push({ ...pool, costBySize });
  }
  return out;
}

/** The cheapest tier for each pair at a given trade size, keyed "tokenIn>tokenOut". */
function cheapestPerPair(quotes          , sizeUsd        )                      {
  const best = new Map                ();
  for (const q of quotes) {
    const c = q.costBySize[sizeUsd];
    if (c === undefined) continue;
    const key = `${q.tokenIn}>${q.tokenOut}`;
    const cur = best.get(key);
    if (!cur || c < (cur.costBySize[sizeUsd] ?? Infinity)) best.set(key, q);
  }
  return best;
}

/* ===== src/core/graph.ts ===== */
/**
 * Graph structures for the Physarum model.
 *
 * Nodes are points on the plane in normalised [0..1] coordinates.
 * Edges are tubes: L is length (cost of passage), D is conductivity (thickness).
 */

                            
            
            
                                                                   
             
                 
     
                                                                               
                                                                            
                                                                                
                               
     
                                 
 

                            
            
            
                                                                 
            
                                                    
            
                                                        
            
 

                        
                     
                     
                                                          
                  
 

                               
                                            
              
                                            
                  
                     
 

function dist(a           , b           )         {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  const dz = (a.z ?? 0) - (b.z ?? 0);
  return Math.hypot(dx, dy, dz);
}

/** Builds a graph from nodes and a list of pairs. Lengths are euclidean. */
function buildGraph(
  nodes             ,
  pairs                         ,
  opts               = {},
)        {
  const rng = opts.rng ?? Math.random;
  const d0 = opts.d0 ?? 0.55;
  const jitter = opts.jitter ?? 0.25;

  const edges              = pairs.map(([a, b]) => ({
    a,
    b,
    L: Math.max(dist(nodes[a], nodes[b]), 1e-6),
    D: d0 + rng() * jitter,
    Q: 0,
  }));

  return { nodes, edges, adj: buildAdjacency(nodes.length, edges) };
}

/**
 * Builds a graph from nodes and explicit edge lengths.
 *
 * Needed for live mode: there an edge length is not a distance on screen but
 * what it actually costs to swap through that pool.
 */
function buildWeightedGraph(
  nodes             ,
  weighted                                            ,
  opts               = {},
)        {
  const rng = opts.rng ?? Math.random;
  const d0 = opts.d0 ?? 0.55;
  const jitter = opts.jitter ?? 0.25;

  const edges              = weighted.map((e) => ({
    a: e.a,
    b: e.b,
    L: Math.max(e.L, 1e-6),
    D: d0 + rng() * jitter,
    Q: 0,
  }));

  return { nodes, edges, adj: buildAdjacency(nodes.length, edges) };
}

function buildAdjacency(nodeCount        , edges             )             {
  const adj             = Array.from({ length: nodeCount }, () => []);
  for (let i = 0; i < edges.length; i++) {
    adj[edges[i].a].push(i);
    adj[edges[i].b].push(i);
  }
  return adj;
}

/* ------------------------------------------------------------------ */
/* Maze                                                                */
/* ------------------------------------------------------------------ */

function find(parent          , i        )         {
  while (parent[i] !== i) {
    parent[i] = parent[parent[i]];
    i = parent[i];
  }
  return i;
}

                                                   
                                                                                         
                          
 

/**
 * A cols x rows lattice with edges removed at random.
 *
 * A spanning tree is built first via union-find, which guarantees the graph is
 * connected and a source-to-sink path always exists. Then part of the removed
 * edges is added back so that alternative routes appear: without them the mold
 * has nothing to choose between.
 */
function generateMaze(cols        , rows        , opts              = {})        {
  const rng = opts.rng ?? Math.random;
  const extra = opts.extraEdgeRatio ?? 0.35;

  const nodes              = [];
  for (let j = 0; j < rows; j++) {
    for (let i = 0; i < cols; i++) {
      nodes.push({ x: cols > 1 ? i / (cols - 1) : 0.5, y: rows > 1 ? j / (rows - 1) : 0.5 });
    }
  }

  const candidates                          = [];
  for (let j = 0; j < rows; j++) {
    for (let i = 0; i < cols; i++) {
      const id = j * cols + i;
      if (i < cols - 1) candidates.push([id, id + 1]);
      if (j < rows - 1) candidates.push([id, id + cols]);
    }
  }

  for (let i = candidates.length - 1; i > 0; i--) {
    const k = Math.floor(rng() * (i + 1));
    const tmp = candidates[i];
    candidates[i] = candidates[k];
    candidates[k] = tmp;
  }

  const parent = nodes.map((_, i) => i);
  const chosen                          = [];
  const rest                          = [];

  for (const pair of candidates) {
    const ra = find(parent, pair[0]);
    const rb = find(parent, pair[1]);
    if (ra !== rb) {
      parent[ra] = rb;
      chosen.push(pair);
    } else {
      rest.push(pair);
    }
  }
  for (const pair of rest) {
    if (rng() < extra) chosen.push(pair);
  }

  return buildGraph(nodes, chosen, opts);
}

/** Lattice edge nodes: entry on the middle left, exit on the middle right. */
function mazeEndpoints(cols        , rows        )                   {
  const mid = Math.floor(rows / 2);
  return [mid * cols, mid * cols + (cols - 1)];
}

/* ===== src/core/pools.ts ===== */
/**
 * Live mode: the pool graph.
 *
 * Nodes are tokens. An edge is a pool between two tokens.
 * Edge length L is what it ACTUALLY costs to route through that pool.
 *
 * The mold minimises total path length, so on this graph it minimises the
 * total cost of a swap. No magic: this is Dijkstra, computed by a biological
 * model instead of a priority queue.
 */



                       
                 
                 
                                             
                 
                               
                       
     
                                                                            
                                                                             
                                                                           
                  
     
                
                                                 
                      
                                                                      
                   
 

                            
                                                     
                       
 

/**
 * What one hop costs, as a fraction of the trade.
 *
 * A pool that carries its own quote uses it — that is a simulation of the swap
 * against real pool state, and nothing here improves on it.
 *
 * Otherwise the pool is constant-product, and for those the cost is not an
 * estimate either. Trading x of a reserve R for the other side:
 *
 *     out / in = (1 - f) * R_out / (R_in + (1 - f) x)
 *     mid      = R_out / R_in
 *     cost     = 1 - (out / in) / mid = 1 - (1 - f) / (1 + (1 - f) x / R_in)
 *
 * liquidityUsd counts both sides of the pool, so the input side is half of it.
 * The older version of this used `fee + S / L`, which understated slippage by
 * a factor of two and drifted badly once the trade approached the pool's size.
 */
function poolCost(pool      , model           )         {
  if (pool.cost !== undefined && isFinite(pool.cost)) {
    return Math.max(pool.cost, 1e-6);
  }
  const f = pool.feeBps / 10_000;
  const reserveIn = pool.liquidityUsd / 2;
  if (!(reserveIn > 0)) return 1;
  const ratio = model.tradeSizeUsd / reserveIn;
  const cost = 1 - (1 - f) / (1 + (1 - f) * ratio);
  return Math.max(Math.min(cost, 1), 1e-6);
}

                            
               
                                                
                   
                                      
 

/**
 * Where the nodes go.
 *
 * The old version put every token on one circle, which on a real pool graph
 * turns into a spider web: with two hubs and a dozen leaves, every edge crosses
 * the middle and nothing is readable.
 *
 * The chain has a shape, so the picture should have it too. A hub is any token
 * that other tokens are anchored on. Hubs go on a spine across the middle;
 * every hub's own tokens fan out in an arc on the side facing away from the
 * other hubs. The result reads as what it is: clusters joined by bridges. The
 * geometry is decorative — it never touches edge lengths, which come from the
 * swap cost alone.
 */
function layoutPoolNodes(
  tokens          ,
  pools        ,
)                                                                                {
  const hubNames           = [];
  const seen = new Set        ();
  for (const p of pools) {
    if (!seen.has(p.tokenA)) {
      seen.add(p.tokenA);
      hubNames.push(p.tokenA);
    }
  }
  // A token anchored on another hub is a bridge, not a hub of its own right
  // here; it still gets a spine slot, which is what makes the bridge visible.
  const hubs = hubNames.filter((h) => tokens.includes(h));
  if (hubs.length === 0) return ring(tokens);

  const leavesOf = new Map                  (hubs.map((h) => [h, []]));
  const placed = new Set(hubs);
  for (const p of pools) {
    if (placed.has(p.tokenB)) continue;
    placed.add(p.tokenB);
    leavesOf.get(p.tokenA)?.push(p.tokenB);
  }
  const orphans = tokens.filter((t) => !placed.has(t));

                                                                        
  const pos = new Map                ();

  // The spine. One hub sits in the middle; several spread across it.
  const H = hubs.length;
  hubs.forEach((h, i) => {
    const x = H === 1 ? 0.5 : 0.5 + (i / (H - 1) - 0.5) * 0.40;
    pos.set(h, { x, y: 0.5, anchor: 'n' });
  });

  hubs.forEach((h, i) => {
    const leaves = leavesOf.get(h) ?? [];
    if (leaves.length === 0) return;
    const centre = pos.get(h) ;
    // Face away from the middle of the spine: the leftmost hub opens left, the
    // rightmost opens right, a lone or middle hub opens both up and down.
    const outward = H === 1 ? 0 : i === 0 ? Math.PI : i === H - 1 ? 0 : -Math.PI / 2;
    // The fan must stay under half a turn: wider than that and the outermost
    // leaves wrap back past the hub and land on the wrong side of it. Within
    // that limit it opens as wide as it can, because the height of the panel is
    // otherwise wasted and everything piles into one horizontal band.
    const spread = H === 1 ? Math.PI * 2 : i > 0 && i < H - 1 ? Math.PI * 0.72 : Math.PI * 0.86;
    const radius = 0.17 + Math.min(0.1, leaves.length * 0.015);

    leaves.forEach((leaf, k) => {
      const t = leaves.length === 1 ? 0.5 : k / (leaves.length - 1);
      const angle = outward + (t - 0.5) * spread;
      const cos = Math.cos(angle);
      const sin = Math.sin(angle);
      // The label goes on the side the node already points to, away from its hub.
      const anchor                        =
        cos < -0.5 ? 'w' : cos > 0.5 ? 'e' : sin > 0 ? 's' : 'n';
      pos.set(leaf, {
        x: centre.x + radius * cos * 1.08,
        y: centre.y + radius * sin * 1.45,
        anchor,
      });
    });
  });

  orphans.forEach((t, i) => {
    const angle = (i / Math.max(1, orphans.length)) * Math.PI * 2;
    pos.set(t, {
      x: 0.5 + 0.46 * Math.cos(angle),
      y: 0.5 + 0.46 * Math.sin(angle),
      anchor: Math.cos(angle) < 0 ? 'w' : 'e',
    });
  });

  // Keep everything inside the canvas with room for a label.
  const clamp = (v        ) => Math.max(0.06, Math.min(0.94, v));
  return tokens.map((label) => {
    const p = pos.get(label) ?? { x: 0.5, y: 0.5, anchor: 'n'          };
    return { x: clamp(p.x), y: clamp(p.y), label, anchor: p.anchor };
  });
}

function ringAnchor(angle        )                        {
  return Math.cos(angle) < -0.5 ? 'w' : Math.cos(angle) > 0.5 ? 'e' : Math.sin(angle) > 0 ? 's' : 'n';
}

function ring(
  tokens          ,
)                                                                                {
  const n = tokens.length;
  return tokens.map((label, i) => {
    const angle = (i / n) * Math.PI * 2 - Math.PI / 2;
    return {
      x: 0.5 + 0.42 * Math.cos(angle),
      y: 0.5 + 0.42 * Math.sin(angle),
      label,
      anchor: ringAnchor(angle),
    };
  });
}

function buildPoolGraph(pools        , model           )            {
  const tokens           = [];
  const idx = new Map                ();
  const put = (s        ) => {
    if (!idx.has(s)) {
      idx.set(s, tokens.length);
      tokens.push(s);
    }
    return idx.get(s) ;
  };
  for (const p of pools) {
    put(p.tokenA);
    put(p.tokenB);
  }

  const nodes = layoutPoolNodes(tokens, pools);

  const weighted = pools.map((p) => ({
    a: idx.get(p.tokenA) ,
    b: idx.get(p.tokenB) ,
    L: poolCost(p, model),
  }));

  return {
    graph: buildWeightedGraph(nodes, weighted),
    tokens,
    indexOf: (s        ) => idx.get(s) ?? -1,
  };
}

/**
 * Picks the two endpoints that make the routing question real: the deepest
 * token on one hub and the deepest on another, so a route has to cross between
 * them. On a single-hub graph it falls back to the two deepest pools.
 *
 * Pools are keyed by tokenA because that is the hub side — every pool the chain
 * reader produces is anchored on one.
 */
function defaultEnds(pools        )                   {
  if (pools.length === 0) return ['', ''];
  const deepest = [...pools].sort((x, y) => y.liquidityUsd - x.liquidityUsd);

  // A hub is any token something else is anchored on. A pool joining two hubs
  // is the bridge, not a destination — routing WETH to VIRTUAL would just show
  // the bridge itself, so those are skipped when picking what to open on.
  const hubNames = new Set(pools.map((p) => p.tokenA));
  const leaves = deepest.filter((p) => !hubNames.has(p.tokenB));
  const pick = leaves.length >= 2 ? leaves : deepest;

  const byHub = new Map              ();
  for (const p of pick) if (!byHub.has(p.tokenA)) byHub.set(p.tokenA, p);
  const across = [...byHub.values()];
  if (across.length >= 2) return [across[0].tokenB, across[1].tokenB];
  return [pick[0].tokenB, pick[1]?.tokenB ?? pick[0].tokenA];
}

/**
 * EXAMPLE DATA, not real pools.
 * This is where the screener plugs in: it already collects RH Chain pools, they
 * just need to be handed over in this shape.
 */
const EXAMPLE_POOLS         = [
  { tokenA: 'WETH', tokenB: 'USDC', feeBps: 5, liquidityUsd: 4_200_000 },
  { tokenA: 'WETH', tokenB: 'HOOD', feeBps: 30, liquidityUsd: 950_000 },
  { tokenA: 'USDC', tokenB: 'HOOD', feeBps: 30, liquidityUsd: 310_000 },
  { tokenA: 'HOOD', tokenB: 'PONS', feeBps: 100, liquidityUsd: 120_000 },
  { tokenA: 'WETH', tokenB: 'PONS', feeBps: 30, liquidityUsd: 480_000 },
  { tokenA: 'PONS', tokenB: 'PHYSARUM', feeBps: 100, liquidityUsd: 60_000 },
  { tokenA: 'WETH', tokenB: 'PHYSARUM', feeBps: 100, liquidityUsd: 95_000 },
  { tokenA: 'USDC', tokenB: 'WALL', feeBps: 30, liquidityUsd: 220_000 },
  { tokenA: 'WALL', tokenB: 'PHYSARUM', feeBps: 100, liquidityUsd: 45_000 },
  { tokenA: 'HOOD', tokenB: 'WALL', feeBps: 30, liquidityUsd: 180_000 },
  { tokenA: 'WETH', tokenB: 'TENDIES', feeBps: 100, liquidityUsd: 75_000 },
  { tokenA: 'TENDIES', tokenB: 'PHYSARUM', feeBps: 100, liquidityUsd: 30_000 },
];

/* ===== src/core/chain.ts ===== */
/**
 * Live mode: reading Uniswap V2 pools straight off Robinhood Chain.
 *
 * No SDK, no indexer, no API key, no backend. Everything here is plain
 * eth_call against the public RPC, encoded and decoded by hand, so the page
 * that shows a route is the same code that fetched the reserves behind it.
 *
 * Scope, stated before anyone asks: V2 only. Uniswap V3 and V4 are also
 * deployed on this chain and carry more volume, but their liquidity is
 * concentrated in ticks, and the slippage estimate in pools.ts (S / L) is only
 * valid for a constant-product pool. Routing V3 honestly means calling their
 * quoter, which is a different job. Rather than quietly mix the two, this
 * module reads V2 and says so.
 *
 * Addresses:
 *   RPC, chain id 4663     docs.robinhood.com/chain/connecting
 *   WETH, USDG             docs.robinhood.com/chain/contracts
 *   UniswapV2Factory       github.com/Uniswap/contracts deployments/4663.md
 */



// Re-exported so the rest of the project, and its tests, keep importing these
// from where they always did.

                                  





const CHAIN_ID = 4663;

const V2_FACTORY = '0x8bceaa40b9acdfaedf85adf4ff01f5ad6517937f';
const WETH = '0x0bd7d308f8e1639fab988df18a8011f41eacad73';
const USDG = '0x5fc5360d0400a0fd4f2af552add042d716f1d168';
const USDG_DECIMALS = 6;


/** Uniswap V2 charges a flat 0.3% on every pool. */
const V2_FEE_BPS = 30;

/** keccak256('PairCreated(address,address,address,uint256)') */
const PAIR_CREATED =
  '0x0d3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9';

/**
 * How far back to ask for PairCreated events.
 *
 * The public RPC accepts an unbounded range — asking from block zero works and
 * returns every pair a hub has ever had. It also returns thousands of them,
 * which is a large response for a page to swallow, so the window is bounded.
 * Three million blocks currently covers a few hundred WETH pairs and a few
 * dozen on the smaller hubs: enough to see the shape, small enough to load.
 */
const LOG_WINDOW_BLOCKS = 3_000_000;

const SEL_V2 = {
  allPairsLength: '0x574f2ba3',
  allPairs: '0x1e3dd18b',
  getPair: '0xe6a43905',
  token0: '0x0dfe1681',
  token1: '0xd21220a7',
  getReserves: '0x0902f1ac',
  symbol: '0x95d89b41',
  decimals: '0x313ce567',
}         ;


/**
 * The hubs.
 *
 * Measured, not assumed. A sample of 200 pairs spread across the whole factory
 * came out 38% paired against WETH and 61% against something else — and almost
 * all of that "something else" was one token, VIRTUAL, which runs its own
 * launchpad. Tokens launched there pair with VIRTUAL and never with WETH.
 *
 * So the pool graph on this chain is not a star. It has two centres joined by a
 * deep VIRTUAL/WETH pool, plus USDG hanging off WETH as the dollar. That is why
 * routing here is a real question: getting from a VIRTUAL-side token to a
 * WETH-side one is a four-node path, and which hub you cross at matters.
 */
                      
                 
                                                        
                  
                   
 

const HUBS        = [
  { symbol: 'WETH', address: WETH, decimals: 18 },
  { symbol: 'VIRTUAL', address: '0xc6911796042b15d7fa4f6cde69e245ddcd3d9c31', decimals: 18 },
  { symbol: 'USDG', address: USDG, decimals: USDG_DECIMALS },
];

const VIRTUAL = HUBS[1].address;

/** The trade sizes the page offers, quoted up front so the control is instant. */
const TRADE_SIZES_USD = [1_000, 10_000, 50_000, 250_000];

                           
               
                                            
              
                                                                          
                 
                
                                                 
                     
                                                       
                       
 

                               
                    
                                                                             
                             
                                                                     
                                 
                                            
                      
                                                    
                  
     
                                                                             
                                                                            
     
                     
 

                              
                                                   
                      
                                                       
                  
                                                             
                  
                                                    
                        
                  
                    
                                                                           
                   
                                                               
                   
                                                                  
                       
     
                                                                             
                                                                              
                                                                        
     
                      
 

/**
 * Prices every hub in dollars, using USDG as the unit.
 *
 * USDG is a dollar by definition. WETH comes from the WETH/USDG pool. Every
 * other hub comes from its pool against WETH. No oracle, no price API — the
 * numbers come out of the same reserves the routing uses, so they cannot
 * disagree with it.
 */
async function fetchHubPrices(io     = {})                                  {
  const out                         = { USDG: 1 };

  const others = HUBS.filter((h) => h.symbol !== 'USDG' && h.symbol !== 'WETH');
  const wanted = [
    { symbol: 'WETH', against: USDG, againstDecimals: USDG_DECIMALS, self: WETH, selfDecimals: 18 },
    ...others.map((h) => ({
      symbol: h.symbol,
      against: WETH,
      againstDecimals: 18,
      self: h.address,
      selfDecimals: h.decimals,
    })),
  ];

  const pairWords = await ethCallBatch(
    wanted.map((x) => ({
      to: V2_FACTORY,
      data: SEL_V2.getPair + addrWord(x.self) + addrWord(x.against),
    })),
    io,
  );
  const live = wanted
    .map((x, i) => ({ x, pair: pairWords[i] ? readAddress(pairWords[i] ) : null }))
    .filter((e)                                                    => !!e.pair && !/^0x0+$/.test(e.pair));

  const calls         = [];
  for (const e of live) {
    calls.push({ to: e.pair, data: SEL_V2.getReserves });
    calls.push({ to: e.pair, data: SEL_V2.token0 });
  }
  const answers = await ethCallBatch(calls, io);

  for (let i = 0; i < live.length; i++) {
    const { x } = live[i];
    const res = readReserves(answers[i * 2] ?? '');
    const t0 = answers[i * 2 + 1];
    if (!res || !t0) continue;
    const selfIsToken0 = readAddress(t0) === x.self.toLowerCase();
    const selfRes = Number(selfIsToken0 ? res[0] : res[1]) / 10 ** x.selfDecimals;
    const otherRes = Number(selfIsToken0 ? res[1] : res[0]) / 10 ** x.againstDecimals;
    if (!selfRes) continue;
    const otherUsd = x.against === USDG ? 1 : out['WETH'];
    if (otherUsd) out[x.symbol] = (otherRes / selfRes) * otherUsd;
  }
  return out;
}

/** WETH in dollars. Its own entry point because the page shows it. */
async function fetchEthPrice(io     = {})                         {
  return (await fetchHubPrices(io))['WETH'] ?? null;
}

const pairKey = (a        , b        ) => [a, b].sort().join('-');
const hexBlock = (n        ) => '0x' + Math.max(0, n).toString(16);

                  
                   
               
                      
 

                             
               
                                                
                
                
 

/**
 * Every pool a hub has, from the factory's own PairCreated events.
 *
 * This replaces walking allPairs(i) one index at a time. The event carries the
 * two tokens and the pool address together, so two requests give a hub's whole
 * list — tokens included — where the index walk needed three calls per pool and
 * could not tell which pools mattered until it had fetched them all.
 *
 * The hub can be either side of a pair (Uniswap orders the two tokens by
 * address), so both positions are asked for.
 */
/**
 * Every pool the factory has opened since a block, in one request.
 *
 * fetchHubPairs below asks per hub and per side, which is two requests each and
 * six in total. That was the largest thing this reader spent: a three-million
 * block log query costs several seconds and a visible slice of whatever budget
 * the public endpoint gives an address, and six of them in a row is what got
 * the routing endpoint answered with 429 and nothing else.
 *
 * The factory emits one event per pool with both tokens in its topics, so a
 * single unfiltered query returns the same information and the splitting by hub
 * happens here, for free. One request instead of six.
 */
async function fetchAllPairs(fromBlock        , io     = {})                    {
  return (
    (await rpc          (
      'eth_getLogs',
      [
        {
          address: V2_FACTORY,
          topics: [PAIR_CREATED],
          fromBlock: hexBlock(fromBlock),
          toBlock: 'latest',
        },
      ],
      io,
    )) ?? []
  );
}

/** A hub's pools, picked out of the factory-wide log above. */
function hubPairsFrom(logs          , hub     )               {
  const want = '0x' + hub.address.replace(/^0x/, '').padStart(64, '0');
  const out               = [];
  for (const l of logs) {
    const hubIsToken0 = l.topics[1] === want;
    const hubIsToken1 = l.topics[2] === want;
    if (!hubIsToken0 && !hubIsToken1) continue;
    out.push({
      // data is (address pair, uint allPairsLength); the pair is the first word
      pair: readAddress(l.data.slice(0, 66)),
      other: readAddress(hubIsToken0 ? l.topics[2] : l.topics[1]),
      block: Number(BigInt(l.blockNumber)),
    });
  }
  return out.sort((a, b) => a.block - b.block);
}

async function fetchHubPairs(
  hub     ,
  fromBlock        ,
  io     = {},
)                        {
  const topic = (a        ) => '0x' + a.replace(/^0x/, '').padStart(64, '0');
  const query = (topics                   ) =>
    rpc          (
      'eth_getLogs',
      [{ address: V2_FACTORY, topics, fromBlock: hexBlock(fromBlock), toBlock: 'latest' }],
      io,
    );

  const [asToken0, asToken1] = [
    await query([PAIR_CREATED, topic(hub.address)]),
    await query([PAIR_CREATED, null, topic(hub.address)]),
  ];

  const read = (logs          , hubIsToken0         )               =>
    (logs ?? []).map((l) => ({
      // data is (address pair, uint allPairsLength); the pair is the first word
      pair: readAddress(l.data.slice(0, 66)),
      other: readAddress(hubIsToken0 ? l.topics[2] : l.topics[1]),
      block: Number(BigInt(l.blockNumber)),
    }));

  return [...read(asToken0, true), ...read(asToken1, false)].sort((a, b) => a.block - b.block);
}

/**
 * Reads what is actually tradable on each hub.
 *
 * Per hub: take its newest pools, price the reserves, drop the empty ones, keep
 * the deepest few. Then join the hubs to each other, because without those
 * bridges the graph is a set of islands and there is nothing to route.
 */
async function fetchLivePools(options              = {})                        {
  const perHubScan = options.perHubScan ?? 30;
  const minUsd = options.minUsd ?? 2_000;
  const perHub = options.perHub ?? 4;
  const windowBlocks = options.windowBlocks ?? LOG_WINDOW_BLOCKS;
  // Pacing has to travel with the transport options, not be dropped here: the
  // server reads the chain more slowly than a browser does, and for a while it
  // was asking for that politely and being ignored.
  const io     = {
    rpcUrl: options.rpcUrl,
    fetcher: options.fetcher,
    pauseMs: options.pauseMs,
    retries: options.retries,
    fallbackUrl: options.fallbackUrl,
  };

  const hubUsd = await fetchHubPrices(io);
  const headHex = await rpc        ('eth_blockNumber', [], io);
  const head = Number(BigInt(headHex));
  const from = head - windowBlocks;

  // One log query for the whole factory, split by hub below. See fetchAllPairs.
  const allLogs = options.pairLogs ?? (await fetchAllPairs(from, io));

                                                                                             
  const found          = [];
  let scanned = 0;

  for (const hub of HUBS) {
    const price = hubUsd[hub.symbol];
    if (!price) continue;
    // One hub failing is not a reason to show nothing. A snapshot missing a
    // hub is still true; an empty page claiming live data is not.
    let records              ;
    let reserves                   ;
    let token0s                   ;
    try {
      records = hubPairsFrom(allLogs, hub).slice(-perHubScan);
      if (records.length === 0) continue;
      reserves = await ethCallBatch(
        records.map((r) => ({ to: r.pair, data: SEL_V2.getReserves })),
        io,
      );
      token0s = await ethCallBatch(
        records.map((r) => ({ to: r.pair, data: SEL_V2.token0 })),
        io,
      );
    } catch {
      continue;
    }
    scanned += records.length;

    const priced          = [];
    for (let i = 0; i < records.length; i++) {
      const res = readReserves(reserves[i] ?? '');
      const t0 = token0s[i];
      if (!res || !t0) continue;
      const hubIsToken0 = readAddress(t0) === hub.address;
      const hubReserve = Number(hubIsToken0 ? res[0] : res[1]) / 10 ** hub.decimals;
      const usd = hubReserve * price * 2;
      if (usd < minUsd) continue;
      priced.push({ pair: records[i].pair, hub: hub.symbol, token: records[i].other, hubReserve, usd });
    }
    priced.sort((a, b) => b.usd - a.usd);
    found.push(...priced.slice(0, perHub));
  }

  // The bridges. Asked for by address rather than by event, because the pools
  // joining two hubs are old and may sit outside the event window.
  const links                            = [];
  for (let i = 0; i < HUBS.length; i++) {
    for (let j = i + 1; j < HUBS.length; j++) links.push({ a: HUBS[i], b: HUBS[j] });
  }
  const linkWords = await ethCallBatch(
    links.map((l) => ({
      to: V2_FACTORY,
      data: SEL_V2.getPair + addrWord(l.a.address) + addrWord(l.b.address),
    })),
    io,
  );
  const linkPairs = links
    .map((l, i) => ({ l, pair: linkWords[i] ? readAddress(linkWords[i] ) : null }))
    .filter((x)                                               => !!x.pair && !/^0x0+$/.test(x.pair));

  const linkCalls         = [];
  for (const x of linkPairs) {
    linkCalls.push({ to: x.pair, data: SEL_V2.getReserves });
    linkCalls.push({ to: x.pair, data: SEL_V2.token0 });
  }
  const linkAnswers = await ethCallBatch(linkCalls, io);

  const already = new Set(found.map((f) => pairKey(f.hub, f.token)));
  const joins          = [];
  for (let i = 0; i < linkPairs.length; i++) {
    const res = readReserves(linkAnswers[i * 2] ?? '');
    const t0 = linkAnswers[i * 2 + 1];
    if (!res || !t0) continue;
    const { a, b } = linkPairs[i].l;
    const aIsToken0 = readAddress(t0) === a.address;
    const aRes = Number(aIsToken0 ? res[0] : res[1]) / 10 ** a.decimals;
    const price = hubUsd[a.symbol];
    if (!price || !aRes) continue;
    const usd = aRes * price * 2;
    if (usd < minUsd) continue;
    if (already.has(pairKey(a.symbol, b.address))) continue;
    joins.push({ pair: linkPairs[i].pair, hub: a.symbol, token: b.address, hubReserve: aRes, usd });
  }

  // Bridges first, so the hubs exist as nodes before anything hangs off them.
  const all = [...joins, ...found];
  const hubSymbolOf = new Map(HUBS.map((h) => [h.address, h.symbol]));
  const unknown = all.filter((f) => !hubSymbolOf.has(f.token));
  const symbols = await ethCallBatch(
    unknown.map((f) => ({ to: f.token, data: SEL_V2.symbol })),
    io,
  );
  const symbolOf = new Map                ();
  unknown.forEach((f, i) => {
    symbolOf.set(f.token, readString(symbols[i] ?? '') ?? f.token.slice(2, 8).toUpperCase());
  });

  const pools             = all.map((f) => ({
    pair: f.pair,
    hub: f.hub,
    token: f.token,
    symbol: hubSymbolOf.get(f.token) ?? symbolOf.get(f.token) ?? '?',
    hubReserve: f.hubReserve,
    liquidityUsd: f.usd,
  }));

  // The same pairs, asked of Uniswap V3. A pair may have a concentrated pool
  // that is far cheaper than the constant-product one, or none at all.
  const hubByName = new Map(HUBS.map((h) => [h.symbol, h]));
  const decimalsOf = new Map                ();
  for (const h of HUBS) decimalsOf.set(h.address, h.decimals);

  const amountInOf = (tokenIn        , sizeUsd        )         => {
    const hub = HUBS.find((h) => h.address === tokenIn);
    const price = hub ? hubUsd[hub.symbol] : undefined;
    const decimals = hub?.decimals ?? 18;
    if (!price || !(price > 0)) return 0n;
    const units = (sizeUsd / price) * 10 ** decimals;
    return BigInt(Math.max(1, Math.round(units)));
  };

  const v3                         = {};
  try {
    const wanted = pools
      .map((p) => ({ tokenIn: hubByName.get(p.hub)?.address ?? '', tokenOut: p.token }))
      .filter((p) => p.tokenIn && p.tokenOut && p.tokenIn !== p.tokenOut);
    if (wanted.length > 0) {
      const v3pools = await findV3Pools(wanted, io);
      const quotes = await quoteV3(v3pools, amountInOf, TRADE_SIZES_USD, io);
      for (const [key, q] of cheapestPerPair(quotes, TRADE_SIZES_USD[1])) v3[key] = q;
      // keep every tier's ladder, not only the cheapest at one size
      for (const q of quotes) {
        const key = `${q.tokenIn}>${q.tokenOut}`;
        const cur = v3[key];
        if (!cur) v3[key] = q;
      }
    }
  } catch {
    // V3 is an improvement on the estimate, not a requirement for the page.
  }

  return { pools, hubUsd, v3, blockNumber: head, scanned, pairLogs: allLogs };
}

/**
 * Live pools in the shape the solver eats.
 *
 * Symbols are made unique before they become graph nodes: two freshly launched
 * tokens sharing a ticker is normal, and silently merging them into one node
 * would invent a route that does not exist.
 */
function toPools(
  snapshot              ,
  tradeSizeUsd         = TRADE_SIZES_USD[1],
)                              {
  const used = new Map                ();
  const label = (token        , symbol        ) => {
    const existing = used.get(token);
    if (existing) return existing;
    const taken = new Set(used.values());
    let name = symbol;
    let n = 2;
    while (taken.has(name)) name = `${symbol} (${n++})`;
    used.set(token, name);
    return name;
  };
  const hubAddress = new Map(HUBS.map((h) => [h.symbol, h.address]));

  return snapshot.pools.map((p) => {
    const hubAddr = hubAddress.get(p.hub) ?? p.hub;
    const base                            = {
      tokenA: label(hubAddr, p.hub),
      tokenB: label(p.token, p.symbol),
      feeBps: V2_FEE_BPS,
      liquidityUsd: p.liquidityUsd,
      venue: 'v2',
    };

    // If a concentrated pool quotes the same hop cheaper, route through it and
    // say so. The comparison is like for like: both numbers are the fraction of
    // the trade lost, at this trade size.
    const quote = snapshot.v3[`${hubAddr}>${p.token}`];
    const quoted = quote?.costBySize[tradeSizeUsd];
    if (quoted === undefined) return base;

    const v2Cost = poolCost(base, { tradeSizeUsd });
    if (quoted >= v2Cost) return base;

    return { ...base, cost: quoted, venue: 'v3', feeTier: quote.fee };
  });
}

/* ===== src/core/solver.ts ===== */
/**
 * The Physarum polycephalum model.
 *
 * Tero A., Takagi S., Saigusa T., Ito K., Bebber D.P., Fricker M.D.,
 * Yumiki K., Kobayashi R., Nakagaki T.
 * "Rules for Biologically Inspired Adaptive Network Design"
 * Science 327, 439 (2010). DOI: 10.1126/science.1177894
 *
 * The whole organism is two equations:
 *
 *   Q_ij = D_ij * (p_i - p_j) / L_ij          flux through a tube
 *   dD_ij/dt = f(|Q_ij|) - D_ij               tube adaptation
 *   f(Q) = Q^g / (1 + Q^g)
 *
 * A tube that carries flow thickens. A tube that doesn't, dies.
 * There is nothing else to it.
 *
 * IMPORTANT. The CURRENT I0 is fixed at the source, not the pressure at both
 * ends. With fixed pressures the total flux decays together with the
 * conductivities and the whole network fades to zero. With fixed current the
 * flux along the surviving path stays near I0 and the system reaches
 * equilibrium.
 */

                                        

                                
                                                                 
              
                                                                                                 
             
                          
              
                                          
                      
     
                                                                 
    
                                                                              
                                                                             
                                                                               
                                                    
     
                        
                                                                
                
                     
 

const DEFAULTS                                       = {
  I0: 1,
  g: 1.8,
  dt: 0.15,
  relaxIters: 60,
  dMin: 1e-4,
  pairsPerStep: 1,
};

class Physarum {
           graph       ;
  /** Food nodes. Exactly two means a fixed source and sink. More means a random pair each step. */
           food          ;
           opts                                      ;

  pressures              ;
  steps = 0;

          rng              ;
          acc                      = null;
          source        ;
          sink        ;

  constructor(graph       , food          , options                = {}) {
    if (food.length < 2) throw new Error('At least two food nodes are required');
    this.graph = graph;
    this.food = food.slice();
    this.opts = { ...DEFAULTS, ...stripRng(options) };
    this.rng = options.rng ?? Math.random;
    this.pressures = new Float64Array(graph.nodes.length);
    this.source = food[0];
    this.sink = food[1];
  }

          pickPair()       {
    if (this.food.length === 2) {
      this.source = this.food[0];
      this.sink = this.food[1];
      return;
    }
    const n = this.food.length;
    const i = Math.floor(this.rng() * n);
    let j = Math.floor(this.rng() * (n - 1));
    if (j >= i) j++;
    this.source = this.food[i];
    this.sink = this.food[j];
  }

  /**
   * Solves Kirchhoff's system with Gauss-Seidel relaxation.
   *
   * Interior node:  p_i = ( SUM c_ij * p_j ) / SUM c_ij
   * Source node:    p_i = ( SUM c_ij * p_j + I0 ) / SUM c_ij
   * Sink is pinned: p_sink = 0
   *
   * where c_ij = D_ij / L_ij is the edge conductance.
   */
          relax()       {
    const { nodes, edges, adj } = this.graph;
    const p = this.pressures;
    const { I0, relaxIters } = this.opts;

    for (let iter = 0; iter < relaxIters; iter++) {
      for (let i = 0; i < nodes.length; i++) {
        if (i === this.sink) {
          p[i] = 0;
          continue;
        }
        const inc = adj[i];
        let num = 0;
        let den = 0;
        for (let k = 0; k < inc.length; k++) {
          const e = edges[inc[k]];
          const other = e.a === i ? e.b : e.a;
          const c = e.D / e.L;
          num += c * p[other];
          den += c;
        }
        if (den <= 0) {
          p[i] = 0;
          continue;
        }
        if (i === this.source) num += I0;
        p[i] = num / den;
      }
    }
  }

  /** One step: solve pressures, compute fluxes, update conductivities. */
  step()       {
    const { edges } = this.graph;
    const p = this.pressures;
    const { g, dt, dMin, pairsPerStep } = this.opts;

    const k = this.food.length > 2 ? Math.max(1, pairsPerStep) : 1;
    if (!this.acc || this.acc.length !== edges.length) {
      this.acc = new Float64Array(edges.length);
    }
    const acc = this.acc;
    acc.fill(0);

    for (let round = 0; round < k; round++) {
      this.pickPair();
      this.relax();

      for (let i = 0; i < edges.length; i++) {
        const e = edges[i];
        const q = (e.D / e.L) * (p[e.a] - p[e.b]);
        e.Q = q;

        const pow = Math.pow(Math.abs(q), g);
        acc[i] += pow / (1 + pow);
      }
    }

    for (let i = 0; i < edges.length; i++) {
      const e = edges[i];
      e.D += dt * (acc[i] / k - e.D);
      if (e.D < dMin) e.D = dMin;
    }
    this.steps++;
  }

  run(n        )       {
    for (let i = 0; i < n; i++) this.step();
  }

  maxD()         {
    let m = 0;
    for (const e of this.graph.edges) if (e.D > m) m = e.D;
    return m || 1;
  }

  /**
   * Indices of the surviving tubes.
   *
   * The threshold is relative by default: a fraction of the thickest tube.
   * That is correct in single source-sink mode, where the network collapses
   * onto one path.
   *
   * In network mode (food in many nodes) a relative threshold lies: a tube to
   * a far node only carries flow in a small fraction of the sampled pairs, so
   * its equilibrium thickness is inherently small and it gets cut along with
   * the dead ones. Pass an absolute threshold there — dead tubes decay to dMin
   * and separate from the living ones by an order of magnitude.
   */
  surviving(threshold                                = 0.25)           {
    const cut =
      typeof threshold === 'number' ? this.maxD() * threshold : threshold.absolute;
    const out           = [];
    for (let i = 0; i < this.graph.edges.length; i++) {
      if (this.graph.edges[i].D > cut) out.push(i);
    }
    return out;
  }

  /** Total length of the surviving tubes. This is the network cost. */
  networkLength(threshold                                = 0.25)         {
    let total = 0;
    for (const i of this.surviving(threshold)) total += this.graph.edges[i].L;
    return total;
  }
}

function stripRng(o               ) {
  const { rng: _rng, ...rest } = o;
  return rest;
}

/* ===== src/core/dijkstra.ts ===== */
/**
 * Plain Dijkstra. Used only as a control: the mold must arrive at exactly the
 * same path.
 */

                                        

                               
                   
                                                                       
                  
                                     
                  
 

function shortestPath(graph       , source        , sink        )               {
  const n = graph.nodes.length;
  const dist = new Float64Array(n).fill(Infinity);
  const prevNode = new Int32Array(n).fill(-1);
  const prevEdge = new Int32Array(n).fill(-1);
  const visited = new Uint8Array(n);

  dist[source] = 0;

  for (;;) {
    let u = -1;
    let best = Infinity;
    for (let i = 0; i < n; i++) {
      if (!visited[i] && dist[i] < best) {
        best = dist[i];
        u = i;
      }
    }
    if (u === -1) break;
    visited[u] = 1;
    if (u === sink) break;

    for (const ei of graph.adj[u]) {
      const e = graph.edges[ei];
      const v = e.a === u ? e.b : e.a;
      const nd = dist[u] + e.L;
      if (nd < dist[v] - 1e-12) {
        dist[v] = nd;
        prevNode[v] = u;
        prevEdge[v] = ei;
      }
    }
  }

  if (!isFinite(dist[sink])) return { distance: Infinity, nodes: [], edges: [] };

  const nodes           = [];
  const edges           = [];
  let cur = sink;
  while (cur !== -1) {
    nodes.push(cur);
    if (prevEdge[cur] !== -1) edges.push(prevEdge[cur]);
    cur = prevNode[cur];
  }
  nodes.reverse();
  edges.reverse();

  return { distance: dist[sink], nodes, edges };
}

/* ===== src/core/route.ts ===== */
/**
 * Turning a set of pools into an answer.
 *
 * This is the part the endpoint serves and the part worth checking, so it lives
 * here rather than inside a handler: it takes pools and two tokens and returns
 * the route, with no network of its own.
 *
 * The mould's answer and Dijkstra's are both computed, and both are returned.
 * The model is proven to converge on the shortest path, so if the two disagree
 * the fault is here — and saying so in the response is cheaper than being
 * caught at it.
 */





                      
               
             
                     
                         
                                                                               
                  
                  
 

                            
                  
                         
              
                                                               
                                       
                                                                        
                 
 

                             
                
                   
 

const pct = (x        ) => +(x * 100).toFixed(4);
/** Pools are undirected, so a pair is keyed by its two labels in a fixed order. */
const hopKey = (a        , b        ) => [a, b].sort().join(' -> ');

function planRoute(
  pools        ,
  from        ,
  to        ,
  tradeSizeUsd        ,
  options                     = {},
)                         {
  const { graph, tokens, indexOf } = buildPoolGraph(pools, { tradeSizeUsd });
  const a = indexOf(from);
  const b = indexOf(to);
  if (a < 0 || b < 0 || a === b) return { error: 'unknown or identical tokens', tokens };

  const mould = new Physarum(graph, [a, b], { I0: 1, g: 1.8, dt: 0.12 });
  mould.run(options.steps ?? 1200);
  const moulded = mould.networkLength(0.25);

  const best = shortestPath(graph, a, b);
  const finite = isFinite(best.distance);

  const byPair = new Map              ();
  for (const p of pools) byPair.set(hopKey(p.tokenA, p.tokenB), p);

  const hops        = best.edges.map((ei) => {
    const e = graph.edges[ei];
    const x = graph.nodes[e.a].label ?? '';
    const y = graph.nodes[e.b].label ?? '';
    const pool = byPair.get(hopKey(x, y));
    return {
      from: x,
      to: y,
      venue: pool?.venue ?? 'v2',
      feeTier: pool?.feeTier ?? null,
      quoted: pool?.cost !== undefined,
      costPct: pool ? pct(poolCost(pool, { tradeSizeUsd })) : 0,
    };
  });

  return {
    route: best.nodes.map((i) => graph.nodes[i].label ?? ''),
    costPct: finite ? pct(best.distance) : null,
    hops,
    mould: { steps: mould.steps, tubesLeft: mould.surviving(0.25).length, costPct: pct(moulded) },
    dijkstra: { costPct: finite ? pct(best.distance) : null },
    agree: finite && Math.abs(moulded - best.distance) < 1e-3,
  };
}

/* ===== server/route.ts ===== */
/**
 * The routing endpoint.
 *
 * This file is not the one that gets deployed. Vercel compiles each file in
 * api/ on its own and does not carry anything it imports from src/ along with
 * it, so a function written there dies on first call with
 *   Cannot find module '/var/task/src/core/chain.ts'
 * Instead this is bundled into api/route.js at build time — one file, no
 * imports left to resolve. See scripts/build-api.mjs.
 *
 * Everything else on this site shows the organism solving. This lets something
 * else ask it. Give it two tokens and a trade size and it reads the chain, runs
 * the model until the network stops changing, and answers with the route that
 * survived.
 *
 *     /api/route?from=WETH&to=USDG&size=10000
 *
 * Two things are deliberate.
 *
 * The answer carries Dijkstra's result next to the mould's, and a flag saying
 * whether they agree. The model is proven to converge on the shortest path, so
 * a disagreement means this endpoint is wrong — and it says so itself rather
 * than waiting to be caught.
 *
 * The chain's endpoint gives each caller a budget, and a full read used to
 * spend more than one. Six of the requests were log queries three million
 * blocks wide — two per hub — and they are now one query for the whole factory,
 * split by hub here. What is left is cached in two halves: which pools exist
 * changes over days, what is in them changes every block, so the expensive half
 * is held for an hour and the cheap half for a minute.
 *
 * There is also a spare route. The pass-through in api/rpc.ts calls from a
 * different address and therefore has its own budget; whichever has been leaned
 * on recently is the one that refuses, which was measured in both directions an
 * hour apart. Direct is tried first and that is the fallback.
 *
 * And the pool snapshot is held between calls rather than read per request.
 * Reading every pool is a few dozen round trips to the chain, and the public
 * RPC throttles this address hard enough that doing it per request simply does
 * not work. The age of the snapshot is in every answer, so nobody has to take
 * its freshness on trust.
 */
// Deliberately NOT an edge function. Edge rejects any module specifier ending
// in .ts anywhere in the graph, and this project writes them everywhere because
// the test suite runs straight from source through node's type stripping, which
// requires them. The node runtime bundles with esbuild, which resolves both
// spellings. Web Request and Response work here just the same.
// Named rather than namespace imports: the bundler in scripts/build-api.mjs
// flattens these modules into one file, and a flattened module has no object
// to hang a namespace off.



/**
 * How long a snapshot is served before the chain is read again.
 *
 * Seconds was the wrong number. Reading every pool is a few dozen round trips,
 * and the public RPC throttles this address far harder than it throttles a
 * visitor's browser — the first deploy answered `rpc 429` and nothing else. So
 * the snapshot is held for minutes, its exact age is in every answer, and
 * anyone who needs the current block can read it off the response and go check.
 */
const MAX_AGE_MS = 60_000;
/** Which pools exist. Days, not blocks — so this is held far longer. */
const PAIRS_MAX_AGE_MS = 3_600_000;
let cached                                                = null;
let pairs                                                        = null;
/** Two requests arriving together must not both go and read the chain — that
 *  burst is precisely what gets throttled. They share one read instead. */
let inFlight                               = null;

async function snapshot(
  origin        ,
)                                                                     {
  const now = Date.now();
  if (cached && now - cached.at < MAX_AGE_MS) {
    return { snapshot: cached.snapshot, ageMs: now - cached.at, stale: false };
  }
  // Reuse the pool list while it is still young; only its contents are re-read.
  const reuse = pairs && now - pairs.at < PAIRS_MAX_AGE_MS ? pairs.logs : undefined;
  if (!inFlight) {
    inFlight = fetchLivePools({
      rpcUrl: RPC_URL,
      fallbackUrl: `${origin}/api/rpc`,
      pauseMs: 250,
      pairLogs: reuse,
    }).finally(() => {
      inFlight = null;
    });
  }
  try {
    const fresh = await inFlight;
    cached = { at: Date.now(), snapshot: fresh };
    if (!reuse) pairs = { at: Date.now(), logs: fresh.pairLogs };
    return { snapshot: fresh, ageMs: 0, stale: false };
  } catch (err) {
    // A refusal now is not a reason to have nothing to say. The last good
    // snapshot is returned with its real age and marked stale.
    if (cached) return { snapshot: cached.snapshot, ageMs: Date.now() - cached.at, stale: true };
    throw err;
  }
}

const HEADERS                         = {
  'content-type': 'application/json',
  'access-control-allow-origin': '*',
  'cache-control': 'no-store',
};

                  
                 
                
 
const json = (body         , status = 200)         => ({ status, body });

/** The node runtime's response object, as much of it as is used here. */
                        
                     
                                               
                           
 

/**
 * Two calling conventions.
 *
 * Vercel hands a function either a Web Request and expects a Response back, or
 * a node request and response pair. Which one depends on the runtime and on the
 * project, and guessing wrong fails the call instantly with nothing useful in
 * the log. So this answers to both: the work happens once, and only the last
 * step differs.
 */
export default async function handler(
  req                                                                                     ,
  res               ,
)                           {
  let answer        ;
  try {
    answer = await respond(req);
  } catch (err) {
    // Whatever went wrong, say what it was. A bare 500 tells the caller nothing
    // and tells us less.
    const message = err instanceof Error ? err.message : String(err);
    answer = { status: 500, body: { error: 'the endpoint failed', detail: message } };
  }
  if (res && typeof res.end === 'function') {
    res.statusCode = answer.status;
    for (const [k, v] of Object.entries(HEADERS)) res.setHeader(k, v);
    res.end(JSON.stringify(answer.body, null, 2));
    return;
  }
  return new Response(JSON.stringify(answer.body, null, 2), {
    status: answer.status,
    headers: HEADERS,
  });
}

function requestUrl(req                                                     )      {
  const raw = typeof req.url === 'string' ? req.url : '/';
  if (/^https?:\/\//.test(raw)) return new URL(raw);
  const host = (req.headers                                      )?.host ?? 'localhost';
  return new URL(raw, `https://${host}`);
}

/**
 * What the chain will and will not answer from inside this function.
 *
 * The first deploy answered `rpc 429` and nothing else, while the very same
 * requests — one call, a batch of forty, a three-million-block log query — all
 * returned 200 when sent from the edge function next door and from a browser.
 * So the refusal is specific to this function's egress, and guessing which
 * request crosses the line is worse than asking. `?probe=1` sends the three
 * shapes one at a time and reports what came back.
 */
async function probe(origin        )                  {
  const attempt = async (label        , url        , body         ) => {
    const began = Date.now();
    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(body),
      });
      const text = await res.text();
      return { label, status: res.status, ms: Date.now() - began, body: text.slice(0, 160) };
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      return { label, status: null, ms: Date.now() - began, body: `threw: ${detail}` };
    }
  };

  const WETH = '0x0bd7d308f8e1639fab988df18a8011f41eacad73';
  const single = { jsonrpc: '2.0', id: 1, method: 'eth_blockNumber', params: [] };
  const batch = Array.from({ length: 40 }, (_, i) => ({
    jsonrpc: '2.0',
    id: i,
    method: 'eth_call',
    params: [{ to: WETH, data: '0x313ce567' }, 'latest'],
  }));

  const edge = `${origin}/api/rpc`;
  const head = await attempt('direct: eth_blockNumber', RPC_URL, single);
  const forty = await attempt('direct: batch of 40 eth_call', RPC_URL, batch);
  const viaEdge = await attempt('through /api/rpc: eth_blockNumber', edge, single);
  const viaEdgeBatch = await attempt('through /api/rpc: batch of 40 eth_call', edge, batch);

  let logs          = { label: 'through /api/rpc: eth_getLogs over 3M blocks', skipped: 'no head to count back from' };
  try {
    const parsed = JSON.parse(viaEdge.body)                       ;
    if (parsed.result) {
      const from = Number(BigInt(parsed.result)) - 3_000_000;
      logs = await attempt('through /api/rpc: eth_getLogs over 3M blocks', edge, {
        jsonrpc: '2.0',
        id: 1,
        method: 'eth_getLogs',
        params: [
          {
            address: '0x8bceaa40b9acdfaedf85adf4ff01f5ad6517937f',
            topics: [
              '0x0d3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9',
              '0x' + WETH.slice(2).padStart(64, '0'),
            ],
            fromBlock: '0x' + from.toString(16),
            toBlock: 'latest',
          },
        ],
      });
    }
  } catch {
    /* head.body was not json; the skipped note above stands */
  }

  return json({
    probe: 'sent from inside this function, one request at a time, no retries',
    results: [head, forty, viaEdge, viaEdgeBatch, logs],
  });
}

async function respond(
  req                                                                                     ,
)                  {
  const url = requestUrl(req                                                       );
  if (url.searchParams.get('probe')) return probe(url.origin);
  const size = Number(url.searchParams.get('size') ?? 10_000);
  if (!isFinite(size) || size <= 0) {
    return json({ error: 'size must be a positive number of dollars' }, 400);
  }

  let snap              ;
  let ageMs        ;
  let stale         ;
  try {
    ({ snapshot: snap, ageMs, stale } = await snapshot(url.origin));
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    return json({ error: 'the chain did not answer', detail }, 502);
  }

  const pools = toPools(snap, size);
  if (pools.length < 2) return json({ error: 'no pools were readable just now' }, 502);

  const from = url.searchParams.get('from');
  const to = url.searchParams.get('to');
  if (!from || !to) {
    const tokens = [...new Set(pools.flatMap((p) => [p.tokenA, p.tokenB]))];
    return json({
      usage: '/api/route?from=WETH&to=USDG&size=10000',
      block: snap.blockNumber,
      tokens,
      note: 'Symbols as they appear on the chain. Two tokens may share one; they are kept apart by address.',
    });
  }

  const plan = planRoute(pools, from, to, size);
  if ('error' in plan) return json({ ...plan, from, to }, 400);

  return json({
    from,
    to,
    tradeSizeUsd: size,
    block: snap.blockNumber,
    snapshotAgeMs: ageMs,
    snapshotStale: stale,
    ...plan,
    disclaimer:
      'A quote is true for its block and nothing more. Re-check against the pool before swapping.',
  });
}
